<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INBook_X1" failures="2" tests="21" name="tests.Login" time="156.556" errors="0" timestamp="2025-04-18T10:38:43 IST" skipped="1">
  <testcase classname="tests.Login" name="verifyLoginIntoApplicationUsingValidCredentials" time="5.809"/>
  <testcase classname="tests.Login" name="verifyLoginIntoApplicationUsingInValidCredentials" time="9.054"/>
  <testcase classname="tests.Login" name="verifyLoginIntoApplicationUsingInValidEmailAndValidPassword" time="5.594"/>
  <testcase classname="tests.Login" name="verifyLoginIntoApplicationUsingValidEmailAndInValidPassword" time="5.358"/>
  <testcase classname="tests.Login" name="verifyLoginIntoApplicationWithoutProvidingAnyCredentials" time="5.795"/>
  <testcase classname="tests.Login" name="verifyForgottonPasswordOptionIsAvailable" time="4.394"/>
  <testcase classname="tests.Login" name="verifyLoginIntoTheApplicationUsingKeyboardKeys" time="5.456"/>
  <testcase classname="tests.Login" name="verifyPlaceHoldersOfFieldsInLoginPage" time="4.656"/>
  <testcase classname="tests.Login" name="verifyBrowsingBackAfterLogin" time="6.102"/>
  <testcase classname="tests.Login" name="verifyBrowsingBackAfterLogout" time="7.520"/>
  <testcase classname="tests.Login" name="verifyLoginIntoAccountUsingInactiveCredentials" time="5.334"/>
  <testcase classname="tests.Login" name="verifyNumberOfUnsuccessfulLoginAttempt" time="10.276"/>
  <testcase classname="tests.Login" name="verifyloginPasswordFieldForVisibility" time="4.094"/>
  <testcase classname="tests.Login" name="verifyPasswordIsNotVisisbleInPageSource" time="5.596">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at tests.Login.verifyPasswordIsNotVisisbleInPageSource(Login.java:155)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyPasswordIsNotVisisbleInPageSource -->
  <testcase classname="tests.Login" name="verifyLoggingIntoApplicationUsingChangedPassword" time="11.934"/>
  <testcase classname="tests.Login" name="verifyLoginPageNavigation" time="37.874"/>
  <testcase classname="tests.Login" name="verifyDifferentWaysOfnavigatingToLoginpage" time="5.550"/>
  <testcase classname="tests.Login" name="verifyLoginPageBreadcrumbURLTitleHeading" time="4.373"/>
  <testcase classname="tests.Login" name="verifyLoginPageUI" time="6.167">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at tests.Login.verifyLoginPageUI(Login.java:378)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyLoginPageUI -->
  <testcase classname="tests.Login" name="verifyLoginInAllEnvironments" time="5.620"/>
  <testcase classname="tests.Login" name="verifyCopyingOfTextIntoPasswordField">
    <skipped/>
  </testcase> <!-- verifyCopyingOfTextIntoPasswordField -->
</testsuite> <!-- tests.Login -->
